//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.30 at 12:26:52 AM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://owl4soul.github.com", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.github.owl4soul.shopping_service.model;
