//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.30 at 12:26:52 AM MSK 
//


package com.github.owl4soul.shopping_service.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for purchase_type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="purchase_type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="tv"/>
 *     &lt;enumeration value="smartphone"/>
 *     &lt;enumeration value="juicer"/>
 *     &lt;enumeration value="headphones"/>
 *     &lt;enumeration value="keyboard"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "purchase_type")
@XmlEnum
public enum PurchaseType {

    @XmlEnumValue("tv")
    TV("tv"),
    @XmlEnumValue("smartphone")
    SMARTPHONE("smartphone"),
    @XmlEnumValue("juicer")
    JUICER("juicer"),
    @XmlEnumValue("headphones")
    HEADPHONES("headphones"),
    @XmlEnumValue("keyboard")
    KEYBOARD("keyboard");
    private final String value;

    PurchaseType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PurchaseType fromValue(String v) {
        for (PurchaseType c: PurchaseType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
